# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["Core.Domain/.", "Core.Domain/"]
COPY ["Infrastructure.Data/.", "Infrastructure.Data/"]
COPY ["Service.Query/.", "Service.Query/"]

WORKDIR /src/Service.Query
RUN dotnet restore

RUN dotnet publish -c Release -o /app/publish

# Stage 2: Final
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Service.Query.dll"]